### PR TITLE
SpringBoot skeleton application.

### PR DESCRIPTION
**Pull request by joaoandremartins**

### CODE REVIEW

**Review by aslo — APPROVED** [review]
LGTM. Are you thinking that all of the separate microservices will live within this one repo? Or separate github repos for each?

**Comment by joaoandremartins** [comment]
Good question. I was thinking they could live in com.google.gfx.services. As in
com.google.gfx.services.exchangerate
com.google.gfx.services.logging
com.google.gfx.services.mail
com.google.gfx.services.notification
com.google.gfx.services.order

**Comment by joaoandremartins** [comment]
Good question. I was thinking they could live in com.google.gfx.services. As in
com.google.gfx.services.exchangerate
com.google.gfx.services.logging
com.google.gfx.services.mail
com.google.gfx.services.notification
com.google.gfx.services.order
com.google.gfx.services.ordermatching

WDYGT?

**Comment by aslo** [comment]
Makes sense to me!

**Comment by meltsufin** [comment]
I think one repo is fine, as long as they're separate maven projects/modules.

**Pull request merged**
